version: '3'

services:
  mannal-db-postgres:
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      image: mannal-postgres
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5435:5432