version: '3'
services:
  http-mennal:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 85:85
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./templates:/etc/nginx/templates
    extra_hosts:
      - "host.docker.internal:host-gateway"
